name: PR Code Checks
on: pull_request
jobs:
  lint:
    if: ${{ github.event.action != 'closed' }}
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i --no-save yarn
      - run: yarn install --immutable --immutable-cache
      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          eslint_flags: '--ext ts,tsx .'
  coverage:
    if: ${{ github.event.action != 'closed' }}
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i --no-save yarn
      - run: yarn install --immutable --immutable-cache
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.github_token }}
          test_script: yarn run test:coverage
  test:
    if: ${{ github.event.action != 'closed' }}
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i --no-save yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn run test:ci
